version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eberle_eats_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eberle
      POSTGRES_PASSWORD: eberle123
      POSTGRES_DB: eberle_eats
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
